---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Creates an ECS Cluster

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName

Outputs:
  ClusterName:
      Value: !Ref Cluster
